// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9lWyAWidZ6KwbhPqFNi_bawiGM232g2A',
    appId: '1:839639242732:web:2886c4e055c56a91d2d2c9',
    messagingSenderId: '839639242732',
    projectId: 'blood-donation-627cb',
    authDomain: 'blood-donation-627cb.firebaseapp.com',
    storageBucket: 'blood-donation-627cb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAJ8AwEtjDRi4cE_HAyid08w31UUFQvmU',
    appId: '1:839639242732:android:7a8188d678be98f7d2d2c9',
    messagingSenderId: '839639242732',
    projectId: 'blood-donation-627cb',
    storageBucket: 'blood-donation-627cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_4JW6hockm-8IFsVzIqcI1j7fe9ljCbs',
    appId: '1:839639242732:ios:768fdc941cdacdc4d2d2c9',
    messagingSenderId: '839639242732',
    projectId: 'blood-donation-627cb',
    storageBucket: 'blood-donation-627cb.appspot.com',
    iosBundleId: 'com.example.bloodDonation',
  );
}
